kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: p7-mysql
  namespace: p7
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
