kind: PersistentVolume
apiVersion: v1
metadata:
  name: databases01
  labels:
    kubernetes.io/cluster-service: "true"
    type: local
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/tbs/k8s/storage/database"
