apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: p7-image-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: p7
    spec:
      containers:
      - name: image
        image: localhost:5000/p7/image:0.0.1
        ports:
        - containerPort: 8887
        securityContext:
        privileged: true
        seLinuxOptions:
          level: "s0:c123,c456"
