apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: p7
  labels:
    k8s-app: p7
  namespace: p7
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: p7
    spec:
      containers:
      - name: p7
        image: localhost:5000/p7/api:0.0.1
        livenessProbe:
          httpGet:
            path: /p7/_ah/health
            port: 8888
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        env:
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: p7-db01-mysql
                key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: p7
  namespace: p7
  labels:
    k8s-app: p7
spec:
  ports:
  - port: 80
    targetPort: 8888
  selector:
    k8s-app: p7

