// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "p7": img TestHelpers
//
// Command:
// $ goagen
// --design=github.com/markusklems/p7/cmd/api/design
// --out=$(GOPATH)/src/github.com/markusklems/p7/cmd/api
// --version=v1.2.0-dirty

package test
