// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "p7": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/markusklems/p7/cmd/api/design
// --out=$(GOPATH)/src/github.com/markusklems/p7/cmd/api
// --version=v1.2.0-dirty

package app

import (
	"fmt"
	"strings"
)

// LambdaHref returns the resource href.
func LambdaHref(lambdaID interface{}) string {
	paramlambdaID := strings.TrimLeftFunc(fmt.Sprintf("%v", lambdaID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/p7/lambdas/%v", paramlambdaID)
}
