// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "image": public TestHelpers
//
// Command:
// $ goagen
// --design=github.com/markusklems/p7/cmd/image/design
// --out=$(GOPATH)/src/github.com/markusklems/p7/cmd/image
// --version=v1.2.0-dirty

package test
