// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/markusklems/p7/cmd/image/design
// --out=$(GOPATH)/src/github.com/markusklems/p7/cmd/image
// --version=v1.1.0-dirty
//
// API "image": Application Resource Href Factories
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import (
	"fmt"
	"strings"
)

// ImageHref returns the resource href.
func ImageHref(imageID interface{}) string {
	paramimageID := strings.TrimLeftFunc(fmt.Sprintf("%v", imageID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/image/images/%v", paramimageID)
}
