---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: p7-api
  name: p7-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
  selector:
    app: p7-api